using System.ComponentModel.DataAnnotations.Schema;
namespace OneBox.Api.Models;
public sealed class AppUser{public Guid Id{get;set;}=Guid.NewGuid();public string Name{get;set;}="";public string Email{get;set;}="";public string? Phone{get;set;}public string PasswordHash{get;set;}="";public string Role{get;set;}="USER";public bool PhoneVerified{get;set;}=false;public string? OtpHash{get;set;}public DateTime? OtpExpiresAt{get;set;}public int OtpAttempts{get;set;}[NotMapped]public string? TempOtp{get;set;}public double? Latitude{get;set;}public double? Longitude{get;set;}public bool LocationAllowed{get;set;}public DateTime CreatedAt{get;set;}=DateTime.UtcNow;}
public sealed class OneTask{public Guid Id{get;set;}=Guid.NewGuid();public Guid UserId{get;set;}public string Type{get;set;}="GENERAL";public string Title{get;set;}="";public string Status{get;set;}="CREATED";public bool RequiresConfirmation{get;set;}public string PayloadJson{get;set;}="{}";public string? ResultJson{get;set;}public DateTime CreatedAt{get;set;}=DateTime.UtcNow;public DateTime UpdatedAt{get;set;}=DateTime.UtcNow;public string ExecutionKey{get;set;}=Guid.NewGuid().ToString("N");public int AttemptCount{get;set;}=0;public List<TaskStep> Steps{get;set;}=[];}
public sealed class ScheduledTask{public Guid Id{get;set;}=Guid.NewGuid();public Guid UserId{get;set;}public Guid? TaskId{get;set;}public string Type{get;set;}="GENERAL";public string Title{get;set;}="";public string Status{get;set;}="PLANNED";public string TriggerType{get;set;}="TIME";public DateTime? RunAtUtc{get;set;}public string? ConditionJson{get;set;}public DateTime? NextCheckAtUtc{get;set;}public DateTime? LastCheckedAtUtc{get;set;}public string? NotificationStatus{get;set;}public string PayloadJson{get;set;}="{}";public DateTime CreatedAt{get;set;}=DateTime.UtcNow;public DateTime UpdatedAt{get;set;}=DateTime.UtcNow;public int AttemptCount{get;set;}}
public sealed class TaskStep{public Guid Id{get;set;}=Guid.NewGuid();public Guid TaskId{get;set;}public int StepOrder{get;set;}public string Name{get;set;}="";public string Status{get;set;}="PENDING";public string? Detail{get;set;}public DateTime? CompletedAt{get;set;}}
public sealed class AuditEvent{public Guid Id{get;set;}=Guid.NewGuid();public Guid UserId{get;set;}public Guid? TaskId{get;set;}public string EventType{get;set;}="";public string Detail{get;set;}="";public DateTime CreatedAt{get;set;}=DateTime.UtcNow;}
public sealed class Booking{public Guid Id{get;set;}=Guid.NewGuid();public Guid UserId{get;set;}public Guid TaskId{get;set;}public string Provider{get;set;}="";public string Category{get;set;}="";public string ProviderReference{get;set;}="";public DateTime ScheduledAt{get;set;}public decimal Amount{get;set;}public string Status{get;set;}="CONFIRMED";public string? ProviderUrl{get;set;}}

public sealed class ProviderSelection{public Guid Id{get;set;}=Guid.NewGuid();public Guid UserId{get;set;}public Guid TaskId{get;set;}public string ProviderId{get;set;}="";public string ProviderName{get;set;}="";public string Category{get;set;}="";public double? DistanceKm{get;set;}public double? Rating{get;set;}public int? RatingCount{get;set;}public string? PriceLevel{get;set;}public string? Address{get;set;}public string? WebsiteUrl{get;set;}public DateTime CreatedAt{get;set;}=DateTime.UtcNow;public bool Active{get;set;}=true;}
public sealed class PaymentTransaction{public Guid Id{get;set;}=Guid.NewGuid();public Guid TaskId{get;set;}public Guid UserId{get;set;}public string Provider{get;set;}="";public decimal ProviderAmount{get;set;}public decimal PlatformFee{get;set;}public decimal Total{get;set;}public string Currency{get;set;}="INR";public string Status{get;set;}="CREATED";public string? ExternalReference{get;set;}public DateTime CreatedAt{get;set;}=DateTime.UtcNow;public DateTime UpdatedAt{get;set;}=DateTime.UtcNow;}
public sealed class ProviderHealth{public Guid Id{get;set;}=Guid.NewGuid();public string Provider{get;set;}="";public string Status{get;set;}="HEALTHY";public double SuccessRate{get;set;}=100;public int TotalAttempts{get;set;}public int SuccessfulAttempts{get;set;}public DateTime LastCheckedAt{get;set;}=DateTime.UtcNow;public string? LastError{get;set;}}
