CREATE DATABASE IF NOT EXISTS onebox CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'onebox'@'%' IDENTIFIED BY 'change-me';
GRANT ALL PRIVILEGES ON onebox.* TO 'onebox'@'%';
FLUSH PRIVILEGES;
