using System.Security.Cryptography;using System.Text;using System.Text.Json;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using OneBox.Api.Data;using OneBox.Api.Models;using OneBox.Api.Services;
namespace OneBox.Api.Controllers;
[Authorize,ApiController,Route("api/payments")]
public sealed class PaymentController(OneBoxDb db,IPaymentOrchestrator payments,IConfiguration cfg):ControllerBase{
 decimal GetPlatformFee()=>cfg["Payments:PlatformFee"] is string fee && decimal.TryParse(fee,out var parsed) && parsed>=0 ? decimal.Round(parsed,2) : 20m;
 [HttpPost("quote")]public IActionResult Quote(PaymentQuoteRequest request){if(request.ProviderAmount<0)return BadRequest(new{message="Amount cannot be negative."});return Ok(payments.Quote(request.ProviderAmount,GetPlatformFee()));}
 [HttpPost("checkout")]public async Task<IActionResult> Checkout(PaymentCheckoutRequest request,CancellationToken ct){if(request.ProviderAmount<0)return BadRequest(new{message="Amount cannot be negative."});var uid=Guid.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)!.Value);var task=await db.Tasks.SingleOrDefaultAsync(x=>x.Id==request.TaskId&&x.UserId==uid,ct);if(task is null)return NotFound(new{message="Task not found for the current user."});var platformFee=GetPlatformFee(); var q=payments.Quote(request.ProviderAmount,platformFee);var tx=new PaymentTransaction{UserId=uid,TaskId=request.TaskId,Provider=request.Provider,ProviderAmount=q.ProviderAmount,PlatformFee=q.PlatformFee,Total=q.Total,Status="CHECKOUT_CREATED"};db.PaymentTransactions.Add(tx);await db.SaveChangesAsync(ct);var session=payments.CreateExternalCheckout(request.Provider,q.ProviderAmount,q.PlatformFee,request.ReturnUrl);tx.ExternalReference=tx.Id.ToString("N");tx.Status=session.Status;tx.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync(ct);return Ok(new{transactionId=tx.Id,session});}
 [HttpGet("task/{taskId:guid}")]public async Task<IActionResult> Status(Guid taskId,CancellationToken ct){var uid=Guid.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)!.Value);var tx=await db.PaymentTransactions.Where(x=>x.TaskId==taskId&&x.UserId==uid).OrderByDescending(x=>x.CreatedAt).FirstOrDefaultAsync(ct);return tx is null?NotFound():Ok(tx);}
 [AllowAnonymous,HttpPost("webhook/{provider}")]public async Task<IActionResult> Webhook(string provider,CancellationToken ct){var secret=HttpContext.RequestServices.GetRequiredService<IConfiguration>()[$"Payments:{provider}:WebhookSecret"];if(string.IsNullOrWhiteSpace(secret))return StatusCode(503,new{message="Payment webhook secret is not configured."});Request.EnableBuffering();using var sr=new StreamReader(Request.Body,Encoding.UTF8,leaveOpen:true);var body=await sr.ReadToEndAsync(ct);Request.Body.Position=0;var signature=Request.Headers["X-ONEBOX-SIGNATURE"].FirstOrDefault()??"";using var h=new HMACSHA256(Encoding.UTF8.GetBytes(secret));var expected=Convert.ToHexString(h.ComputeHash(Encoding.UTF8.GetBytes(body))).ToLowerInvariant();if(!CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(signature),Encoding.UTF8.GetBytes(expected)))return Unauthorized();using var doc=JsonDocument.Parse(body);if(!doc.RootElement.TryGetProperty("transactionId",out var id)||!Guid.TryParse(id.GetString(),out var txid))return BadRequest(new{message="transactionId is required."});var tx=await db.PaymentTransactions.SingleOrDefaultAsync(x=>x.Id==txid&&x.Provider.Equals(provider,StringComparison.OrdinalIgnoreCase),ct);if(tx is null)return NotFound();tx.Status=doc.RootElement.TryGetProperty("status",out var st)?st.GetString()??"UNKNOWN":"UNKNOWN";tx.UpdatedAt=DateTime.UtcNow;if(doc.RootElement.TryGetProperty("externalReference",out var er))tx.ExternalReference=er.GetString();await db.SaveChangesAsync(ct);return Ok(new{received=true});}
}
public sealed record PaymentQuoteRequest(decimal ProviderAmount,decimal PlatformFee=0);public sealed record PaymentCheckoutRequest(Guid TaskId,string Provider,decimal ProviderAmount,decimal PlatformFee,string? ReturnUrl);
