using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using OneBox.Api.Data;using OneBox.Api.Services;using System.Text.Json;using Microsoft.EntityFrameworkCore;using OneBox.Api.Models;
namespace OneBox.Api.Controllers;
[Authorize,ApiController,Route("api/providers")]
public sealed class ProvidersController(OneBoxDb db,GooglePlacesService places):ControllerBase{Guid Id=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
 [HttpGet("nearby")]public async Task<IActionResult> Nearby(string category,CancellationToken ct){var u=await db.Users.FindAsync([Id],ct);if(u is null)return NotFound();if(!u.LocationAllowed||u.Latitude is null||u.Longitude is null)return BadRequest(new{code="LOCATION_REQUIRED",message="Allow location access first."});var items=await places.SearchAsync(category,u.Latitude.Value,u.Longitude.Value,ct);return Ok(items);}
 [HttpGet("compare")]public async Task<IActionResult> Compare(string category,CancellationToken ct){var u=await db.Users.FindAsync([Id],ct);if(u is null)return NotFound();if(!u.LocationAllowed||u.Latitude is null||u.Longitude is null)return BadRequest(new{code="LOCATION_REQUIRED",message="Allow location access first."});var items=await places.SearchAsync(category,u.Latitude.Value,u.Longitude.Value,ct);var ranked=items.Select(x=>new{provider=x,score=Score(x)}).OrderByDescending(x=>x.score).ToList();return Ok(new{category,generatedAtUtc=DateTime.UtcNow,items=ranked});}
 [HttpPost("select")]public async Task<IActionResult> Select(ProviderSelectionRequest request,CancellationToken ct){var task=await db.Tasks.SingleOrDefaultAsync(x=>x.Id==request.TaskId&&x.UserId==Id,ct);if(task is null)return NotFound(new{message="Task not found."});if(string.IsNullOrWhiteSpace(request.ProviderId)||string.IsNullOrWhiteSpace(request.ProviderName))return BadRequest(new{message="Provider id and name are required."});var old=await db.ProviderSelections.Where(x=>x.UserId==Id&&x.TaskId==request.TaskId&&x.Active).ToListAsync(ct);foreach(var x in old)x.Active=false;var selected=new ProviderSelection{UserId=Id,TaskId=request.TaskId,ProviderId=request.ProviderId,ProviderName=request.ProviderName,Category=request.Category,DistanceKm=request.DistanceKm,Rating=request.Rating,RatingCount=request.RatingCount,PriceLevel=request.PriceLevel,Address=request.Address,WebsiteUrl=request.WebsiteUrl};db.ProviderSelections.Add(selected);var plan=JsonSerializer.Deserialize<AgentPlan>(task.PayloadJson);if(plan is not null)task.PayloadJson=JsonSerializer.Serialize(plan with {Details=plan.Details+" | Selected provider: "+request.ProviderName+" ("+request.ProviderId+")"});task.Status=task.Status=="OPTIONS_READY"?"READY":task.Status;task.UpdatedAt=DateTime.UtcNow;db.AuditEvents.Add(new AuditEvent{UserId=Id,TaskId=task.Id,EventType="PROVIDER_SELECTED",Detail=request.ProviderName});await db.SaveChangesAsync(ct);return Ok(new{selected.Id,selected.ProviderId,selected.ProviderName,taskId=task.Id,status=task.Status});}
 private static double Score(ProviderOption x){var distance=x.DistanceKm??99;var rating=x.Rating??0;var ratingCount=Math.Min(x.RatingCount??0,10000);var price=x.PriceLevel switch{"PRICE_LEVEL_INEXPENSIVE"=>1.0,"PRICE_LEVEL_MODERATE"=>0.75,"PRICE_LEVEL_EXPENSIVE"=>0.45,"PRICE_LEVEL_VERY_EXPENSIVE"=>0.2,_=>0.6};return Math.Round((1/(1+distance))*0.35+(rating/5)*0.45+(Math.Log10(ratingCount+1)/4)*0.1+price*0.1,4);}

}
